# Link the C runtime statically on Windows so the helper runs on a clean PC without the
# Visual C++ Redistributable installed.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
